return {
 ["content"]={
  ["files"]={
   ["context"]="bin",
   ["context.lua"]="bin",
   ["luametatex"]="bin",
   ["luatex"]="bin",
   ["mtxrun"]="bin",
   ["mtxrun.lua"]="bin",
  },
  ["metadata"]={
   ["directories"]=1,
   ["files"]=6,
   ["path"]="selfautoparent:texmf-osx-64",
   ["remappings"]=0,
  },
  ["remap"]={},
 },
 ["date"]="2021-08-26",
 ["root"]="selfautoparent:texmf-osx-64",
 ["time"]="03:18:39",
 ["type"]="files",
 ["uuid"]="3421ec43-4ac1-a7a0-9100-19c9de19bdd1",
 ["version"]="1.100",
}