return {
 ["content"]={
  ["files"]={
   ["context"]="bin",
   ["context.lua"]="bin",
   ["luametatex"]="bin",
   ["luatex"]="bin",
   ["mtxrun"]="bin",
   ["mtxrun.lua"]="bin",
  },
  ["metadata"]={
   ["directories"]=1,
   ["files"]=6,
   ["path"]="selfautoparent:texmf-osx-64",
   ["remappings"]=0,
  },
  ["remap"]={},
 },
 ["date"]="2021-09-04",
 ["root"]="selfautoparent:texmf-osx-64",
 ["time"]="08:53:10",
 ["type"]="files",
 ["uuid"]="289ca79d-4cc5-81f9-9235-bccab74b993d",
 ["version"]="1.100",
}