return {
 ["content"]={
  ["files"]={
   ["context"]="bin",
   ["context.lua"]="bin",
   ["luametatex"]="bin",
   ["luatex"]="bin",
   ["mtxrun"]="bin",
   ["mtxrun.lua"]="bin",
  },
  ["metadata"]={
   ["directories"]=1,
   ["files"]=6,
   ["path"]="selfautoparent:texmf-osx-64",
   ["remappings"]=0,
  },
  ["remap"]={},
 },
 ["date"]="2021-10-11",
 ["root"]="selfautoparent:texmf-osx-64",
 ["time"]="07:19:03",
 ["type"]="files",
 ["uuid"]="7a0fa2f0-4ef5-aa75-1dc4-7a9432b7dbe1",
 ["version"]="1.100",
}