return {
 ["content"]={
  ["files"]={
   ["context"]="bin",
   ["context.lua"]="bin",
   ["luametatex"]="bin",
   ["luatex"]="bin",
   ["mtxrun"]="bin",
   ["mtxrun.lua"]="bin",
  },
  ["metadata"]={
   ["directories"]=1,
   ["files"]=6,
   ["path"]="selfautoparent:texmf-osx-64",
   ["remappings"]=0,
  },
  ["remap"]={},
 },
 ["date"]="2021-09-21",
 ["root"]="selfautoparent:texmf-osx-64",
 ["time"]="07:49:19",
 ["type"]="files",
 ["uuid"]="d50fde6b-4e91-a5ab-5c2f-95a660f00ce2",
 ["version"]="1.100",
}